spring:
  application:
    name: feed-service
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

server:
  port: 8097

auth:
  secret: changekeyandlocation

