spring:
  application:
    name: feed-service
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    preferIpAddress: true
    hostname: host.docker.internal
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8083/eureka
    healthcheck:
      enabled: true

server:
  port: 8097

auth:
  secret: changekeyandlocation

